### ISSUE TITLE
The python, node, and go Dockerfiles should use multi-stage builds

### ISSUE THREAD

**Issue by jonjohnsonjr** [GoogleCloudPlatform/cloud-code-samples#100]
The hello-world for go produces a 346 MB image right now. Switching over to use gcr.io/distroless/base cuts that down to 19.8MB. We could probably cut that down further with gcr.io/distroless/static and static compilation, but that makes using delve a bit of a pain.

Similarly, the node and python examples both use a 300MB+ base image without using a multi-stage build to cut down the size of the resulting image.

**Comment by grayside** [comment]
It is not typical to use multi-stage images with Python and Node, though some could be used. Cloud Run samples use debian slim images to minimize the size.

**Comment by ace-n** [comment]
[Node](https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/1103) and [Python](https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/1105) have since been moved over to Alpine. (Go was [not moved](https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/1106) due to test failures.)

@jonjohnsonjr  does that address your concerns here?

**Comment by grayside** [comment]
Closing due to no response after over 1 year.
