### ISSUE TITLE
java-questbook example with profile cloudbuild not working

### ISSUE THREAD

**Issue by matihost** [GoogleCloudPlatform/cloud-code-samples#198]
After adding project-id and kubeContext to skaffold.yaml in java-questbook example and update apiVersion (the generated one is old one):

```yaml
apiVersion: skaffold/v2alpha1
kind: Config
....
- name: cloudbuild
  build:
    googleCloudBuild:
      projectId: my-project-id
  deploy: 	
    kubeContext: 'gke_myproject-id_zone_cluster-id'  
```

The build is failing:
```
starting build "abcdedf12345abffeeeeebeeeee"

FETCHSOURCE
Fetching storage object: gs://my-project-id_cloudbuild/source/my-project-id-abcdef1234567890abcdef.tar.gz#123456789
Copying gs://my-project-id_cloudbuild/source/my-project-id-abcdef1234567890abcdef.tar.gz#123456789...
/ [0 files][ 0.0 B/ 7.7 KiB] 
/ [1 files][ 7.7 KiB/ 7.7 KiB] 
Operation completed over 1 objects/7.7 KiB. 
BUILD
Already have image (with digest): gcr.io/cloud-builders/mvn
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: frontend @ 
[ERROR] Could not find the selected project in the reactor: frontend -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/mvn" failed: exit status 1
```

because cloud build command is:

-c "mvn -Duser.home=$HOME -Djib.console=plain jib:_skaffold-fail-if-jib-out-of-date -Djib.requiredVersion=1.4.0 --projects frontend --also-make package jib:build -Djib.containerize=frontend -Dimage=gcr.io/my-project-id/java-guestbook-frontend:latest"

The problem is:
 --projects frontend 
because it means Maven build module in "frontend" subdirecotry, while gs contains "frontend" as root.
The way to fix is either:
 --projects :frontend 
or remove the --projects flag.

Secondly the version is cloud run is different than the one used in pom.xml plugin (1.7.0 generated, 1.8.0 latest jib version) - gcloud should use the same version.
However It seems I cannot be changed it from https://skaffold.dev/docs/references/yaml/ configuration.

**Comment by askmeegs** [comment]
Hi there, 

1. re: Jib versions -- Looking at the java guestbook `pom.xml`, I see the Jib version as `2.4.0`, version been updated in that file throughout this year, eg. [this commit](https://github.com/GoogleCloudPlatform/cloud-code-samples/commit/c6e0e94224b2edc216ad992c2fd70d635f1fe1a0#diff-025982a4851ad337054b33bbfc2cb011865f11c5c3fcec1cc1ab0d7822e6be25) from Feb. 


2. I attempted to reproduce your bug but was unable to - using the cloudbuild profile and my own GCP project + GKE cluster, I was able to successfully run `skaffold run`, the images built with Jib, and successfully deployed to my cluster. 
```
[INFO] Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, cloudcode.guestbook.frontend.FrontendApplication]
[INFO] 
[INFO] Built and pushed image as gcr.io/megan-fall20/java-guestbook/java-guestbook-frontend
[INFO] 
[INFO] A new version of Jib (2.7.0) is available (currently using 2.4.0). Update your build configuration to use the latest features and fixes!
[INFO] https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/CHANGELOG.md
[INFO] Please see https://github.com/GoogleContainerTools/jib/blob/master/docs/privacy.md for info on disabling this update check.
[INFO] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

I'm not sure why I don't see the `gs` / subdir error, when you do. Because Jib uses Maven, it's possible one or both of those tools changed between versions in how they deal with subdirectories + modules. If you try this again with the latest sample pom.xml, and keep seeing this issue, feel free to reopen this bug.
