### ISSUE TITLE
[BUG] arm64 macOS - Unable to select existing skaffold.yaml

### ISSUE THREAD

**Issue by JCzz** [GoogleCloudPlatform/cloud-code-samples#920]
`Invalid Data: Skaffold configuration file is not selected.`

![image](https://user-images.githubusercontent.com/1861398/146215689-c7e4406a-8d21-493a-a52a-c857331ffada.png)

**Comment by etanshaul** [comment]
hey @JCzz I assume you do have a `skaffold.yaml` file in your project?

One thing you might check that I've seen in the past is the file type association of `*.yaml`. To do this:
- Right click on the `skaffold.yaml` file in the IDE's file explorer
- Click "Override file type"
- Then click "YAML"

This might resolve the problem if the culprit was that `.yaml` files were being associated as txt files (and Cloud Code then unable to parse it).

**Comment by JCzz** [comment]
Thanks @etanshaul 

It did not work. I ended up creating a new project and copied the files.
